/**
 * NO-FOMO.AI — AI News Platform
 * רשימת מקורות מאומתים — גרסה 2
 *
 * כל מקור כולל מלא:
 * - id, name, url, rss?
 * - type, tier (1=חיוני | 2=חשוב | 3=משלים)
 * - lang, topics, reliability (1-5)
 * - credit: מידע לתצוגה + קרדיט ב-UI
 */

export type SourceType =
  | "company_blog"    // בלוג רשמי של חברה
  | "research_org"    // מוסד מחקר אקדמי/עצמאי
  | "media"           // מדיה טכנולוגית
  | "newsletter"      // ניוזלטר / Substack
  | "forum"           // פורום / קהילה
  | "twitter_account" // חשבון X/Twitter
  | "youtube"         // ערוץ YouTube
  | "podcast"         // פודקאסט
  | "paper_tracker"   // מעקב אחר מאמרים
  | "github"          // GitHub repos / trending
  | "discord"         // Discord server
  | "israeli"         // מקורות ישראליים
  | "aggregator"      // aggregator אחר שנעקוב אחריו

export type Topic =
  | "LLMs"
  | "tools"
  | "research"
  | "robotics"
  | "safety"
  | "policy"
  | "vision"
  | "audio"
  | "agents"
  | "open_source"
  | "business"
  | "hardware"
  | "startups"
  | "education"
  | "data_science"

/** מידע לתצוגת קרדיט ב-UI לכל ידיעה שמגיעה מהמקור הזה */
export interface SourceCredit {
  /** שם מלא לתצוגה — "OpenAI Blog", "@karpathy" */
  display_name: string
  /** URL ישיר ללחיצה מה-UI — תמיד ל-profile/homepage של המקור */
  profile_url: string
  /** Favicon/logo — ניתן להשתמש ב-Google Favicons API אוטומטית */
  favicon_url: string
  /** תגית קצרה שמופיעה ב-badge: "Newsletter" | "Blog" | "@Twitter" | "YouTube" | ... */
  label: string
  /** Twitter handle אם רלוונטי, לתצוגת @ */
  twitter_handle?: string
  /** תיאור קצר אחד למשפט — מוצג ב-tooltip ב-UI */
  tagline: string
}

export interface Source {
  id: string
  name: string
  url: string
  rss?: string
  type: SourceType
  tier: 1 | 2 | 3
  lang: "en" | "he" | "multi"
  topics: Topic[]
  reliability: 1 | 2 | 3 | 4 | 5
  notes?: string
  /** מידע לקרדיט ב-UI */
  credit: SourceCredit
}

// helper לבניית favicon URL אוטומטי
const favicon = (domain: string) =>
  `https://www.google.com/s2/favicons?domain=${domain}&sz=64`

// ─────────────────────────────────────────────────────────────────────────────
// TIER 1 — חיוני: חברות AI — בלוגים רשמיים
// ─────────────────────────────────────────────────────────────────────────────
export const SOURCES: Source[] = [
  {
    id: "anthropic-blog",
    name: "Anthropic Blog",
    url: "https://www.anthropic.com/news",
    // אין RSS רשמי — מכוסה ע"י VentureBeat/TechCrunch
    type: "company_blog",
    tier: 1,
    lang: "en",
    topics: ["LLMs", "safety", "research", "agents"],
    reliability: 5,
    notes: "יצרנית Claude — כל עדכון כאן הוא חדשות",
    credit: {
      display_name: "Anthropic",
      profile_url: "https://www.anthropic.com/news",
      favicon_url: favicon("anthropic.com"),
      label: "Blog",
      twitter_handle: "AnthropicAI",
      tagline: "AI safety company — יוצרי Claude",
    },
  },
  {
    id: "openai-blog",
    name: "OpenAI Blog",
    url: "https://openai.com/blog",
    rss: "https://openai.com/blog/rss.xml",
    type: "company_blog",
    tier: 1,
    lang: "en",
    topics: ["LLMs", "tools", "research", "agents", "safety"],
    reliability: 5,
    notes: "GPT-4o, o3, Sora, DALL-E — עדכונים רשמיים",
    credit: {
      display_name: "OpenAI",
      profile_url: "https://openai.com/blog",
      favicon_url: favicon("openai.com"),
      label: "Blog",
      twitter_handle: "OpenAI",
      tagline: "יוצרי ChatGPT ו-GPT-4",
    },
  },
  {
    id: "google-deepmind-blog",
    name: "Google DeepMind Blog",
    url: "https://deepmind.google/discover/blog",
    rss: "https://blog.google/technology/ai/rss/",
    type: "company_blog",
    tier: 1,
    lang: "en",
    topics: ["LLMs", "research", "robotics", "safety", "vision"],
    reliability: 5,
    notes: "Gemini, AlphaFold, Gemma — מחקר חזיתי",
    credit: {
      display_name: "Google DeepMind",
      profile_url: "https://deepmind.google/discover/blog",
      favicon_url: favicon("deepmind.google"),
      label: "Blog",
      twitter_handle: "GoogleDeepMind",
      tagline: "מחקר AI ראשוני של Google",
    },
  },
  {
    id: "meta-ai-blog",
    name: "Meta AI Blog",
    url: "https://ai.meta.com/blog",
    rss: "https://engineering.fb.com/category/ai-research/feed/",
    type: "company_blog",
    tier: 1,
    lang: "en",
    topics: ["LLMs", "open_source", "research", "vision"],
    reliability: 5,
    notes: "Llama 3, open source AI",
    credit: {
      display_name: "Meta AI",
      profile_url: "https://ai.meta.com/blog",
      favicon_url: favicon("ai.meta.com"),
      label: "Blog",
      twitter_handle: "MetaAI",
      tagline: "יוצרי Llama — מוביל קוד פתוח",
    },
  },
  {
    id: "mistral-blog",
    name: "Mistral AI Blog",
    url: "https://mistral.ai/news",
    // אין RSS רשמי — מכוסה ע"י מדיה
    type: "company_blog",
    tier: 1,
    lang: "en",
    topics: ["LLMs", "open_source"],
    reliability: 5,
    credit: {
      display_name: "Mistral AI",
      profile_url: "https://mistral.ai/news",
      favicon_url: favicon("mistral.ai"),
      label: "Blog",
      twitter_handle: "MistralAI",
      tagline: "Mistral / Mixtral — open source LLMs מובילים",
    },
  },
  {
    id: "huggingface-blog",
    name: "Hugging Face Blog",
    url: "https://huggingface.co/blog",
    rss: "https://huggingface.co/blog/feed.xml",
    type: "company_blog",
    tier: 1,
    lang: "en",
    topics: ["open_source", "tools", "research", "LLMs"],
    reliability: 5,
    credit: {
      display_name: "Hugging Face",
      profile_url: "https://huggingface.co/blog",
      favicon_url: favicon("huggingface.co"),
      label: "Blog",
      twitter_handle: "huggingface",
      tagline: "מרכז קוד פתוח AI — מודלים, datasets, demos",
    },
  },
  {
    id: "microsoft-ai-blog",
    name: "Microsoft AI Blog",
    url: "https://blogs.microsoft.com/ai",
    rss: "https://blogs.microsoft.com/ai/feed",
    type: "company_blog",
    tier: 1,
    lang: "en",
    topics: ["LLMs", "tools", "agents", "business"],
    reliability: 5,
    credit: {
      display_name: "Microsoft AI",
      profile_url: "https://blogs.microsoft.com/ai",
      favicon_url: favicon("microsoft.com"),
      label: "Blog",
      twitter_handle: "MSFTResearch",
      tagline: "Azure AI, Copilot, השקעה ב-OpenAI",
    },
  },
  {
    id: "google-ai-blog",
    name: "Google AI Blog",
    url: "https://blog.google/technology/ai",
    rss: "https://blog.google/technology/ai/rss",
    type: "company_blog",
    tier: 1,
    lang: "en",
    topics: ["LLMs", "tools", "research", "vision"],
    reliability: 5,
    credit: {
      display_name: "Google AI",
      profile_url: "https://blog.google/technology/ai",
      favicon_url: favicon("blog.google"),
      label: "Blog",
      tagline: "Gemini, Bard, Google Cloud AI",
    },
  },
  {
    id: "xai-blog",
    name: "xAI Blog",
    url: "https://x.ai/blog",
    // אין RSS — 404
    type: "company_blog",
    tier: 1,
    lang: "en",
    topics: ["LLMs", "research"],
    reliability: 4,
    credit: {
      display_name: "xAI (Grok)",
      profile_url: "https://x.ai/blog",
      favicon_url: favicon("x.ai"),
      label: "Blog",
      tagline: "חברת Elon Musk — Grok LLM",
    },
  },
  {
    id: "cohere-blog",
    name: "Cohere Blog",
    url: "https://cohere.com/blog",
    // לא RSS סטנדרטי — ללא feed
    type: "company_blog",
    tier: 1,
    lang: "en",
    topics: ["LLMs", "business", "tools"],
    reliability: 4,
    credit: {
      display_name: "Cohere",
      profile_url: "https://cohere.com/blog",
      favicon_url: favicon("cohere.com"),
      label: "Blog",
      tagline: "Enterprise AI — Command R+",
    },
  },
  {
    id: "perplexity-blog",
    name: "Perplexity Blog",
    url: "https://blog.perplexity.ai",
    // 404 — ללא feed
    type: "company_blog",
    tier: 1,
    lang: "en",
    topics: ["tools", "LLMs", "agents"],
    reliability: 4,
    credit: {
      display_name: "Perplexity AI",
      profile_url: "https://blog.perplexity.ai",
      favicon_url: favicon("perplexity.ai"),
      label: "Blog",
      twitter_handle: "perplexity_ai",
      tagline: "AI search engine — צומח מהר",
    },
  },
  {
    id: "runway-blog",
    name: "Runway Research",
    url: "https://runwayml.com/research",
    type: "company_blog",
    tier: 1,
    lang: "en",
    topics: ["vision", "tools"],
    reliability: 4,
    credit: {
      display_name: "Runway",
      profile_url: "https://runwayml.com/research",
      favicon_url: favicon("runwayml.com"),
      label: "Blog",
      twitter_handle: "runwayml",
      tagline: "Gen-3 Alpha — AI video generation",
    },
  },
  {
    id: "elevenlabs-blog",
    name: "ElevenLabs Blog",
    url: "https://elevenlabs.io/blog",
    // XML encoding שגוי — ללא feed
    type: "company_blog",
    tier: 1,
    lang: "en",
    topics: ["audio", "tools"],
    reliability: 4,
    credit: {
      display_name: "ElevenLabs",
      profile_url: "https://elevenlabs.io/blog",
      favicon_url: favicon("elevenlabs.io"),
      label: "Blog",
      twitter_handle: "elevenlabsio",
      tagline: "AI voice generation מוביל",
    },
  },
  {
    id: "stability-ai-blog",
    name: "Stability AI",
    url: "https://stability.ai/news",
    // XML שגוי — ללא feed
    type: "company_blog",
    tier: 1,
    lang: "en",
    topics: ["vision", "open_source", "audio"],
    reliability: 4,
    credit: {
      display_name: "Stability AI",
      profile_url: "https://stability.ai/news",
      favicon_url: favicon("stability.ai"),
      label: "Blog",
      twitter_handle: "StabilityAI",
      tagline: "Stable Diffusion — AI image generation",
    },
  },
  {
    id: "nvidia-ai-blog",
    name: "NVIDIA AI Blog",
    url: "https://blogs.nvidia.com/blog/category/deep-learning",
    rss: "https://blogs.nvidia.com/feed",
    type: "company_blog",
    tier: 1,
    lang: "en",
    topics: ["hardware", "research", "LLMs"],
    reliability: 5,
    notes: "GPU/hardware — כל AI רץ על NVIDIA",
    credit: {
      display_name: "NVIDIA",
      profile_url: "https://blogs.nvidia.com/blog/category/deep-learning",
      favicon_url: favicon("nvidia.com"),
      label: "Blog",
      tagline: "GPU + hardware AI — התשתית של כל המודלים",
    },
  },
  {
    id: "groq-blog",
    name: "Groq Blog",
    url: "https://groq.com/news",
    type: "company_blog",
    tier: 2,
    lang: "en",
    topics: ["hardware", "LLMs"],
    reliability: 4,
    credit: {
      display_name: "Groq",
      profile_url: "https://groq.com/news",
      favicon_url: favicon("groq.com"),
      label: "Blog",
      tagline: "LPU chip — inference מהיר מאוד",
    },
  },
  {
    id: "together-ai-blog",
    name: "Together AI Blog",
    url: "https://www.together.ai/blog",
    rss: "https://www.together.ai/blog/rss.xml",
    type: "company_blog",
    tier: 2,
    lang: "en",
    topics: ["open_source", "tools", "LLMs"],
    reliability: 4,
    credit: {
      display_name: "Together AI",
      profile_url: "https://www.together.ai/blog",
      favicon_url: favicon("together.ai"),
      label: "Blog",
      tagline: "Inference + fine-tuning לקוד פתוח",
    },
  },
  {
    id: "replicate-blog",
    name: "Replicate Blog",
    url: "https://replicate.com/blog",
    rss: "https://replicate.com/blog/rss",
    type: "company_blog",
    tier: 2,
    lang: "en",
    topics: ["tools", "open_source"],
    reliability: 4,
    credit: {
      display_name: "Replicate",
      profile_url: "https://replicate.com/blog",
      favicon_url: favicon("replicate.com"),
      label: "Blog",
      tagline: "הרצת מודלים open source ב-cloud",
    },
  },
  {
    id: "scale-ai-blog",
    name: "Scale AI Blog",
    url: "https://scale.com/blog",
    type: "company_blog",
    tier: 2,
    lang: "en",
    topics: ["research", "business", "LLMs"],
    reliability: 4,
    credit: {
      display_name: "Scale AI",
      profile_url: "https://scale.com/blog",
      favicon_url: favicon("scale.com"),
      label: "Blog",
      tagline: "Data labeling + model evaluation",
    },
  },
  {
    id: "langchain-blog",
    name: "LangChain Blog",
    url: "https://blog.langchain.dev",
    rss: "https://blog.langchain.dev/rss.xml",
    type: "company_blog",
    tier: 1,
    lang: "en",
    topics: ["agents", "tools", "open_source"],
    reliability: 4,
    credit: {
      display_name: "LangChain",
      profile_url: "https://blog.langchain.dev",
      favicon_url: favicon("langchain.dev"),
      label: "Blog",
      twitter_handle: "LangChainAI",
      tagline: "LangChain / LangGraph — framework סוכנים מוביל",
    },
  },
  {
    id: "llamaindex-blog",
    name: "LlamaIndex Blog",
    url: "https://www.llamaindex.ai/blog",
    type: "company_blog",
    tier: 2,
    lang: "en",
    topics: ["agents", "tools"],
    reliability: 4,
    credit: {
      display_name: "LlamaIndex",
      profile_url: "https://www.llamaindex.ai/blog",
      favicon_url: favicon("llamaindex.ai"),
      label: "Blog",
      tagline: "RAG + agents framework",
    },
  },
  {
    id: "wandb-blog",
    name: "Weights & Biases Blog",
    url: "https://wandb.ai/blog",
    rss: "https://wandb.ai/blog/feed",
    type: "company_blog",
    tier: 2,
    lang: "en",
    topics: ["tools", "research"],
    reliability: 4,
    credit: {
      display_name: "Weights & Biases",
      profile_url: "https://wandb.ai/blog",
      favicon_url: favicon("wandb.ai"),
      label: "Blog",
      tagline: "MLOps — experiment tracking ו-evaluation",
    },
  },
  {
    id: "bair-blog",
    name: "BAIR Blog (Berkeley AI)",
    url: "https://bair.berkeley.edu/blog",
    rss: "https://bair.berkeley.edu/blog/feed.xml",
    type: "research_org",
    tier: 2,
    lang: "en",
    topics: ["research", "LLMs", "robotics"],
    reliability: 5,
    credit: {
      display_name: "BAIR Blog",
      profile_url: "https://bair.berkeley.edu/blog",
      favicon_url: favicon("bair.berkeley.edu"),
      label: "Research",
      tagline: "Berkeley AI Research — מחקר אקדמי פורץ דרך",
    },
  },
  {
    id: "aws-ml-blog",
    name: "AWS Machine Learning Blog",
    url: "https://aws.amazon.com/blogs/machine-learning",
    rss: "https://aws.amazon.com/blogs/machine-learning/feed",
    type: "company_blog",
    tier: 2,
    lang: "en",
    topics: ["tools", "business", "LLMs"],
    reliability: 4,
    credit: {
      display_name: "AWS ML",
      profile_url: "https://aws.amazon.com/blogs/machine-learning",
      favicon_url: favicon("aws.amazon.com"),
      label: "Blog",
      tagline: "Amazon Web Services ML — cloud AI applications",
    },
  },
  {
    id: "apple-ml-research",
    name: "Apple ML Research",
    url: "https://machinelearning.apple.com",
    rss: "https://machinelearning.apple.com/rss/articles.rss",
    type: "company_blog",
    tier: 2,
    lang: "en",
    topics: ["research", "LLMs", "vision"],
    reliability: 4,
    credit: {
      display_name: "Apple ML Research",
      profile_url: "https://machinelearning.apple.com",
      favicon_url: favicon("apple.com"),
      label: "Research",
      tagline: "Apple ML — on-device AI ומחקר privacy",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // TIER 1 — מוסדות מחקר + מעקב מאמרים
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: "arxiv-cs-ai",
    name: "arXiv cs.AI",
    url: "https://arxiv.org/list/cs.AI/recent",
    rss: "https://rss.arxiv.org/rss/cs.AI",
    type: "paper_tracker",
    tier: 1,
    lang: "en",
    topics: ["research"],
    reliability: 5,
    credit: {
      display_name: "arXiv cs.AI",
      profile_url: "https://arxiv.org/list/cs.AI/recent",
      favicon_url: favicon("arxiv.org"),
      label: "Research",
      tagline: "preprints AI — המקור הגולמי לכל מחקר חדש",
    },
  },
  {
    id: "arxiv-cs-cl",
    name: "arXiv cs.CL (NLP/LLMs)",
    url: "https://arxiv.org/list/cs.CL/recent",
    rss: "https://rss.arxiv.org/rss/cs.CL",
    type: "paper_tracker",
    tier: 1,
    lang: "en",
    topics: ["LLMs", "research"],
    reliability: 5,
    credit: {
      display_name: "arXiv cs.CL",
      profile_url: "https://arxiv.org/list/cs.CL/recent",
      favicon_url: favicon("arxiv.org"),
      label: "Research",
      tagline: "NLP ו-LLMs preprints — הכי רלוונטי לרוב הידיעות",
    },
  },
  {
    id: "arxiv-cs-lg",
    name: "arXiv cs.LG",
    url: "https://arxiv.org/list/cs.LG/recent",
    rss: "https://rss.arxiv.org/rss/cs.LG",
    type: "paper_tracker",
    tier: 1,
    lang: "en",
    topics: ["research"],
    reliability: 5,
    credit: {
      display_name: "arXiv cs.LG",
      profile_url: "https://arxiv.org/list/cs.LG/recent",
      favicon_url: favicon("arxiv.org"),
      label: "Research",
      tagline: "Machine Learning preprints",
    },
  },
  {
    id: "papers-with-code",
    name: "Papers With Code",
    url: "https://paperswithcode.com/latest",
    rss: "https://paperswithcode.com/rss",
    type: "paper_tracker",
    tier: 1,
    lang: "en",
    topics: ["research", "open_source"],
    reliability: 5,
    credit: {
      display_name: "Papers With Code",
      profile_url: "https://paperswithcode.com/latest",
      favicon_url: favicon("paperswithcode.com"),
      label: "Research",
      tagline: "מאמרים + קוד + State of the Art leaderboards",
    },
  },
  {
    id: "hf-daily-papers",
    name: "Hugging Face Daily Papers",
    url: "https://huggingface.co/papers",
    rss: "https://huggingface.co/blog/feed.xml",
    type: "paper_tracker",
    tier: 1,
    lang: "en",
    topics: ["research", "LLMs"],
    reliability: 5,
    credit: {
      display_name: "HF Daily Papers",
      profile_url: "https://huggingface.co/papers",
      favicon_url: favicon("huggingface.co"),
      label: "Research",
      tagline: "מאמרים נבחרים יומי ע\"י קהילת HuggingFace",
    },
  },
  {
    id: "nature-ml",
    name: "Nature Machine Intelligence",
    url: "https://www.nature.com/natmachintell",
    rss: "https://www.nature.com/natmachintell.rss",
    type: "paper_tracker",
    tier: 2,
    lang: "en",
    topics: ["research"],
    reliability: 5,
    credit: {
      display_name: "Nature MI",
      profile_url: "https://www.nature.com/natmachintell",
      favicon_url: favicon("nature.com"),
      label: "Journal",
      tagline: "כתב עת מחקרי peer-reviewed של Nature",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // TIER 1 — מדיה טכנולוגית
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: "venturebeat-ai",
    name: "VentureBeat AI",
    url: "https://venturebeat.com/ai",
    rss: "https://venturebeat.com/category/ai/feed",
    type: "media",
    tier: 1,
    lang: "en",
    topics: ["LLMs", "tools", "business", "startups"],
    reliability: 4,
    credit: {
      display_name: "VentureBeat",
      profile_url: "https://venturebeat.com/ai",
      favicon_url: favicon("venturebeat.com"),
      label: "Media",
      tagline: "כיסוי עסקי-טכנולוגי AI מקיף",
    },
  },
  {
    id: "mit-tech-review-ai",
    name: "MIT Technology Review AI",
    url: "https://www.technologyreview.com/topic/artificial-intelligence",
    rss: "https://www.technologyreview.com/topic/artificial-intelligence/feed",
    type: "media",
    tier: 1,
    lang: "en",
    topics: ["research", "policy", "safety", "LLMs"],
    reliability: 5,
    credit: {
      display_name: "MIT Tech Review",
      profile_url: "https://www.technologyreview.com/topic/artificial-intelligence",
      favicon_url: favicon("technologyreview.com"),
      label: "Media",
      tagline: "עומק אקדמי + נגישות — מאוד אמין",
    },
  },
  {
    id: "techcrunch-ai",
    name: "TechCrunch AI",
    url: "https://techcrunch.com/category/artificial-intelligence",
    rss: "https://techcrunch.com/category/artificial-intelligence/feed",
    type: "media",
    tier: 1,
    lang: "en",
    topics: ["startups", "business", "tools", "LLMs"],
    reliability: 4,
    credit: {
      display_name: "TechCrunch",
      profile_url: "https://techcrunch.com/category/artificial-intelligence",
      favicon_url: favicon("techcrunch.com"),
      label: "Media",
      tagline: "סיקור startups ועסקים בתחום AI",
    },
  },
  {
    id: "the-verge-ai",
    name: "The Verge AI",
    url: "https://www.theverge.com/ai-artificial-intelligence",
    rss: "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml",
    type: "media",
    tier: 1,
    lang: "en",
    topics: ["tools", "LLMs", "policy", "business"],
    reliability: 4,
    credit: {
      display_name: "The Verge",
      profile_url: "https://www.theverge.com/ai-artificial-intelligence",
      favicon_url: favicon("theverge.com"),
      label: "Media",
      tagline: "כיסוי AI רחב ונגיש לכולם",
    },
  },
  {
    id: "ars-technica-ai",
    name: "Ars Technica AI",
    url: "https://arstechnica.com/ai",
    rss: "https://feeds.arstechnica.com/arstechnica/technology-lab",
    type: "media",
    tier: 2,
    lang: "en",
    topics: ["LLMs", "research", "policy"],
    reliability: 4,
    credit: {
      display_name: "Ars Technica",
      profile_url: "https://arstechnica.com/ai",
      favicon_url: favicon("arstechnica.com"),
      label: "Media",
      tagline: "עמוק וטכני — כתיבה מצוינת",
    },
  },
  {
    id: "wired-ai",
    name: "Wired AI",
    url: "https://www.wired.com/tag/artificial-intelligence",
    rss: "https://www.wired.com/feed/tag/ai/latest/rss",
    type: "media",
    tier: 2,
    lang: "en",
    topics: ["policy", "safety", "LLMs", "business"],
    reliability: 4,
    credit: {
      display_name: "Wired",
      profile_url: "https://www.wired.com/tag/artificial-intelligence",
      favicon_url: favicon("wired.com"),
      label: "Media",
      tagline: "AI, culture & policy",
    },
  },
  {
    id: "the-information-ai",
    name: "The Information AI",
    url: "https://www.theinformation.com/technology/artificial-intelligence",
    type: "media",
    tier: 2,
    lang: "en",
    topics: ["business", "startups", "LLMs"],
    reliability: 5,
    notes: "paywall אבל סקופים עסקיים אמינים מאוד",
    credit: {
      display_name: "The Information",
      profile_url: "https://www.theinformation.com/technology/artificial-intelligence",
      favicon_url: favicon("theinformation.com"),
      label: "Media",
      tagline: "סקופים עסקיים AI — paywall, אמין מאוד",
    },
  },
  {
    id: "marktechpost",
    name: "MarkTechPost",
    url: "https://www.marktechpost.com",
    rss: "https://www.marktechpost.com/feed",
    type: "media",
    tier: 2,
    lang: "en",
    topics: ["research", "LLMs", "tools"],
    reliability: 3,
    credit: {
      display_name: "MarkTechPost",
      profile_url: "https://www.marktechpost.com",
      favicon_url: favicon("marktechpost.com"),
      label: "Media",
      tagline: "ML ו-deep learning research summaries",
    },
  },
  {
    id: "towards-data-science",
    name: "Towards Data Science",
    url: "https://towardsdatascience.com",
    rss: "https://towardsdatascience.com/feed",
    type: "media",
    tier: 2,
    lang: "en",
    topics: ["data_science", "LLMs", "tools"],
    reliability: 3,
    notes: "Medium publication — איכות משתנה, נפח גבוה",
    credit: {
      display_name: "Towards Data Science",
      profile_url: "https://towardsdatascience.com",
      favicon_url: favicon("towardsdatascience.com"),
      label: "Blog",
      tagline: "Medium publication — data science ו-AI tutorials",
    },
  },
  {
    id: "kdnuggets",
    name: "KDnuggets",
    url: "https://www.kdnuggets.com",
    rss: "https://www.kdnuggets.com/feed",
    type: "media",
    tier: 2,
    lang: "en",
    topics: ["data_science", "LLMs", "tools"],
    reliability: 3,
    credit: {
      display_name: "KDnuggets",
      profile_url: "https://www.kdnuggets.com",
      favicon_url: favicon("kdnuggets.com"),
      label: "Media",
      tagline: "AI, ML, data science — news & resources",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // TIER 1 — ניוזלטרים ו-Substacks
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: "the-batch",
    name: "The Batch (DeepLearning.AI)",
    url: "https://www.deeplearning.ai/the-batch",
    rss: "https://www.deeplearning.ai/the-batch/feed/",
    type: "newsletter",
    tier: 1,
    lang: "en",
    topics: ["LLMs", "research", "business"],
    reliability: 5,
    notes: "Andrew Ng's weekly — מאוד אמין ועמוק",
    credit: {
      display_name: "The Batch",
      profile_url: "https://www.deeplearning.ai/the-batch",
      favicon_url: favicon("deeplearning.ai"),
      label: "Newsletter",
      twitter_handle: "AndrewYNg",
      tagline: "שבועי של Andrew Ng — ניתוח מעמיק ואמין",
    },
  },
  {
    id: "import-ai",
    name: "Import AI (Jack Clark)",
    url: "https://importai.substack.com",
    rss: "https://importai.substack.com/feed",
    type: "newsletter",
    tier: 1,
    lang: "en",
    topics: ["research", "safety", "policy"],
    reliability: 5,
    notes: "שבועי — מחבר Anthropic לשעבר",
    credit: {
      display_name: "Import AI",
      profile_url: "https://importai.substack.com",
      favicon_url: favicon("substack.com"),
      label: "Newsletter",
      twitter_handle: "jackclarkSF",
      tagline: "Jack Clark — לשעבר Anthropic, עמוק ומקורי",
    },
  },
  {
    id: "tldr-ai",
    name: "TLDR AI",
    url: "https://tldr.tech/ai",
    rss: "https://tldr.tech/api/rss/ai",
    type: "newsletter",
    tier: 1,
    lang: "en",
    topics: ["LLMs", "tools", "research"],
    reliability: 4,
    notes: "620K+ מנויים — יומי, טכני, תמציתי",
    credit: {
      display_name: "TLDR AI",
      profile_url: "https://tldr.tech/ai",
      favicon_url: favicon("tldr.tech"),
      label: "Newsletter",
      tagline: "620K+ מנויים — יומי תמציתי",
    },
  },
  {
    id: "the-rundown-ai",
    name: "The Rundown AI",
    url: "https://www.therundown.ai",
    type: "newsletter",
    tier: 1,
    lang: "en",
    topics: ["LLMs", "tools", "business"],
    reliability: 4,
    notes: "2M+ מנויים — המתחרה הגדול ביותר",
    credit: {
      display_name: "The Rundown AI",
      profile_url: "https://www.therundown.ai",
      favicon_url: favicon("therundown.ai"),
      label: "Newsletter",
      twitter_handle: "rowancheung",
      tagline: "2M+ מנויים — daily AI news",
    },
  },
  {
    id: "the-neuron",
    name: "The Neuron",
    url: "https://www.theneuron.ai",
    type: "newsletter",
    tier: 2,
    lang: "en",
    topics: ["LLMs", "tools", "business"],
    reliability: 3,
    notes: "500K+ מנויים — morning brew style",
    credit: {
      display_name: "The Neuron",
      profile_url: "https://www.theneuron.ai",
      favicon_url: favicon("theneuron.ai"),
      label: "Newsletter",
      tagline: "500K+ מנויים — Morning Brew style לא-טכנאים",
    },
  },
  {
    id: "bens-bites",
    name: "Ben's Bites",
    url: "https://bensbites.beehiiv.com",
    rss: "https://bensbites.co/rss",
    type: "newsletter",
    tier: 2,
    lang: "en",
    topics: ["tools", "startups", "LLMs"],
    reliability: 4,
    credit: {
      display_name: "Ben's Bites",
      profile_url: "https://bensbites.beehiiv.com",
      favicon_url: favicon("bensbites.beehiiv.com"),
      label: "Newsletter",
      twitter_handle: "bentossell",
      tagline: "יומי — כיסוי כלים ו-startups",
    },
  },
  {
    id: "interconnects",
    name: "Interconnects (Nathan Lambert)",
    url: "https://www.interconnects.ai",
    rss: "https://www.interconnects.ai/feed",
    type: "newsletter",
    tier: 1,
    lang: "en",
    topics: ["research", "LLMs", "safety"],
    reliability: 5,
    credit: {
      display_name: "Interconnects",
      profile_url: "https://www.interconnects.ai",
      favicon_url: favicon("interconnects.ai"),
      label: "Newsletter",
      twitter_handle: "natolambert",
      tagline: "Nathan Lambert — RLHF expert, עמוק מאוד",
    },
  },
  {
    id: "ahead-of-ai",
    name: "Ahead of AI (Sebastian Raschka)",
    url: "https://magazine.sebastianraschka.com",
    rss: "https://magazine.sebastianraschka.com/feed",
    type: "newsletter",
    tier: 2,
    lang: "en",
    topics: ["research", "LLMs"],
    reliability: 5,
    credit: {
      display_name: "Ahead of AI",
      profile_url: "https://magazine.sebastianraschka.com",
      favicon_url: favicon("sebastianraschka.com"),
      label: "Newsletter",
      twitter_handle: "rasbt",
      tagline: "Sebastian Raschka — הסבר עמוק של papers",
    },
  },
  {
    id: "one-useful-thing",
    name: "One Useful Thing (Ethan Mollick)",
    url: "https://www.oneusefulthing.org",
    rss: "https://www.oneusefulthing.org/feed",
    type: "newsletter",
    tier: 1,
    lang: "en",
    topics: ["tools", "business", "education"],
    reliability: 5,
    credit: {
      display_name: "One Useful Thing",
      profile_url: "https://www.oneusefulthing.org",
      favicon_url: favicon("oneusefulthing.org"),
      label: "Newsletter",
      twitter_handle: "emollick",
      tagline: "Ethan Mollick (Wharton) — שימושים מעשיים של AI",
    },
  },
  {
    id: "latent-space",
    name: "Latent Space (swyx & Alessio)",
    url: "https://www.latent.space",
    rss: "https://www.latent.space/feed",
    type: "newsletter",
    tier: 1,
    lang: "en",
    topics: ["agents", "tools", "LLMs"],
    reliability: 5,
    notes: "גם podcast — for AI engineers",
    credit: {
      display_name: "Latent Space",
      profile_url: "https://www.latent.space",
      favicon_url: favicon("latent.space"),
      label: "Newsletter",
      twitter_handle: "latentspacepod",
      tagline: "AI engineers podcast + newsletter",
    },
  },
  {
    id: "understanding-ai",
    name: "Understanding AI (Timothy Lee)",
    url: "https://www.understandingai.org",
    rss: "https://www.understandingai.org/feed",
    type: "newsletter",
    tier: 2,
    lang: "en",
    topics: ["LLMs", "policy", "business"],
    reliability: 4,
    credit: {
      display_name: "Understanding AI",
      profile_url: "https://www.understandingai.org",
      favicon_url: favicon("understandingai.org"),
      label: "Newsletter",
      tagline: "Timothy B. Lee — ניתוח תחרות בין חברות AI",
    },
  },
  {
    id: "algorithmic-bridge",
    name: "The Algorithmic Bridge",
    url: "https://www.thealgorithmicbridge.com",
    rss: "https://www.thealgorithmicbridge.com/feed",
    type: "newsletter",
    tier: 2,
    lang: "en",
    topics: ["LLMs", "research", "policy"],
    reliability: 4,
    credit: {
      display_name: "Algorithmic Bridge",
      profile_url: "https://www.thealgorithmicbridge.com",
      favicon_url: favicon("thealgorithmicbridge.com"),
      label: "Newsletter",
      twitter_handle: "TheAlgBridge",
      tagline: "Alberto Romero — הבנה מעמיקה של מושגי AI",
    },
  },
  {
    id: "the-gradient",
    name: "The Gradient",
    url: "https://thegradient.pub",
    rss: "https://thegradient.pub/rss/",
    type: "newsletter",
    tier: 1,
    lang: "en",
    topics: ["research", "LLMs", "safety", "policy"],
    reliability: 5,
    notes: "ניתוחי עומק נדירים — כותבים חוקרים בפועל",
    credit: {
      display_name: "The Gradient",
      profile_url: "https://thegradient.pub",
      favicon_url: favicon("thegradient.pub"),
      label: "Newsletter",
      tagline: "מחקרי AI בעומק — כותבים חוקרים מובילים",
    },
  },
  {
    id: "ieee-spectrum-ai",
    name: "IEEE Spectrum AI",
    url: "https://spectrum.ieee.org/topic/artificial-intelligence",
    rss: "https://spectrum.ieee.org/feeds/topic/artificial-intelligence.rss",
    type: "media",
    tier: 1,
    lang: "en",
    topics: ["research", "hardware", "robotics", "LLMs"],
    reliability: 5,
    notes: "הפרסום הטכני המוביל בעולם — אמין ומעמיק",
    credit: {
      display_name: "IEEE Spectrum",
      profile_url: "https://spectrum.ieee.org/topic/artificial-intelligence",
      favicon_url: favicon("spectrum.ieee.org"),
      label: "Media",
      tagline: "IEEE — הפרסום הטכני-הנדסי המוביל בעולם",
    },
  },
  {
    id: "exponential-view",
    name: "Exponential View",
    url: "https://www.exponentialview.co",
    type: "newsletter",
    tier: 2,
    lang: "en",
    topics: ["policy", "business", "LLMs"],
    reliability: 4,
    credit: {
      display_name: "Exponential View",
      profile_url: "https://www.exponentialview.co",
      favicon_url: favicon("exponentialview.co"),
      label: "Newsletter",
      twitter_handle: "azeem",
      tagline: "Azeem Azhar — AI, policy & business",
    },
  },
  {
    id: "alphasignal",
    name: "AlphaSignal",
    url: "https://alphasignal.ai",
    type: "newsletter",
    tier: 2,
    lang: "en",
    topics: ["research", "open_source", "tools"],
    reliability: 4,
    credit: {
      display_name: "AlphaSignal",
      profile_url: "https://alphasignal.ai",
      favicon_url: favicon("alphasignal.ai"),
      label: "Newsletter",
      tagline: "מעקב papers + repos — ממוקד מפתחים",
    },
  },
  {
    id: "simon-willison",
    name: "Simon Willison's Weblog",
    url: "https://simonwillison.net",
    rss: "https://simonwillison.net/atom/everything",
    type: "newsletter",
    tier: 2,
    lang: "en",
    topics: ["tools", "LLMs", "open_source"],
    reliability: 5,
    credit: {
      display_name: "Simon Willison",
      profile_url: "https://simonwillison.net",
      favicon_url: favicon("simonwillison.net"),
      label: "Blog",
      twitter_handle: "simonw",
      tagline: "Django creator — AI tools deep dives",
    },
  },
  {
    id: "nlp-news",
    name: "NLP News (Sebastian Ruder)",
    url: "https://nlpnews.substack.com",
    rss: "https://nlpnews.substack.com/feed",
    type: "newsletter",
    tier: 2,
    lang: "en",
    topics: ["research", "LLMs"],
    reliability: 5,
    credit: {
      display_name: "NLP News",
      profile_url: "https://nlpnews.substack.com",
      favicon_url: favicon("substack.com"),
      label: "Newsletter",
      twitter_handle: "seb_ruder",
      tagline: "Sebastian Ruder — ניתוח NLP ו-ML advances",
    },
  },
  {
    id: "ai-safety-newsletter",
    name: "AI Safety Newsletter (CAIS)",
    url: "https://newsletter.safe.ai",
    rss: "https://newsletter.safe.ai/feed",
    type: "newsletter",
    tier: 2,
    lang: "en",
    topics: ["safety", "policy", "research"],
    reliability: 5,
    credit: {
      display_name: "AI Safety Newsletter",
      profile_url: "https://newsletter.safe.ai",
      favicon_url: favicon("safe.ai"),
      label: "Newsletter",
      tagline: "Center for AI Safety — safety focused",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // TIER 1 — X/Twitter: חוקרים ומובילי דעה
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: "twitter-karpathy",
    name: "@karpathy (Andrej Karpathy)",
    url: "https://x.com/karpathy",
    type: "twitter_account",
    tier: 1,
    lang: "en",
    topics: ["LLMs", "research", "tools"],
    reliability: 5,
    credit: {
      display_name: "Andrej Karpathy",
      profile_url: "https://x.com/karpathy",
      favicon_url: favicon("x.com"),
      label: "@Twitter",
      twitter_handle: "karpathy",
      tagline: "לשעבר OpenAI + Tesla AI — אחד הקולות הכי אמינים",
    },
  },
  {
    id: "twitter-ylecun",
    name: "@ylecun (Yann LeCun)",
    url: "https://x.com/ylecun",
    type: "twitter_account",
    tier: 1,
    lang: "en",
    topics: ["research", "LLMs", "policy"],
    reliability: 4,
    credit: {
      display_name: "Yann LeCun",
      profile_url: "https://x.com/ylecun",
      favicon_url: favicon("x.com"),
      label: "@Twitter",
      twitter_handle: "ylecun",
      tagline: "Meta AI Chief — ACM Turing Award laureate",
    },
  },
  {
    id: "twitter-sama",
    name: "@sama (Sam Altman)",
    url: "https://x.com/sama",
    type: "twitter_account",
    tier: 1,
    lang: "en",
    topics: ["LLMs", "business", "policy"],
    reliability: 4,
    credit: {
      display_name: "Sam Altman",
      profile_url: "https://x.com/sama",
      favicon_url: favicon("x.com"),
      label: "@Twitter",
      twitter_handle: "sama",
      tagline: "CEO OpenAI",
    },
  },
  {
    id: "twitter-dario",
    name: "@dario_amodei (Dario Amodei)",
    url: "https://x.com/dario_amodei",
    type: "twitter_account",
    tier: 1,
    lang: "en",
    topics: ["safety", "LLMs", "policy"],
    reliability: 5,
    credit: {
      display_name: "Dario Amodei",
      profile_url: "https://x.com/dario_amodei",
      favicon_url: favicon("x.com"),
      label: "@Twitter",
      twitter_handle: "dario_amodei",
      tagline: "CEO Anthropic — עמוק בנושאי safety",
    },
  },
  {
    id: "twitter-demis",
    name: "@demishassabis (Demis Hassabis)",
    url: "https://x.com/demishassabis",
    type: "twitter_account",
    tier: 1,
    lang: "en",
    topics: ["research", "LLMs", "safety"],
    reliability: 5,
    credit: {
      display_name: "Demis Hassabis",
      profile_url: "https://x.com/demishassabis",
      favicon_url: favicon("x.com"),
      label: "@Twitter",
      twitter_handle: "demishassabis",
      tagline: "CEO Google DeepMind",
    },
  },
  {
    id: "twitter-ilyasut",
    name: "@ilyasut (Ilya Sutskever)",
    url: "https://x.com/ilyasut",
    type: "twitter_account",
    tier: 1,
    lang: "en",
    topics: ["research", "safety", "LLMs"],
    reliability: 5,
    credit: {
      display_name: "Ilya Sutskever",
      profile_url: "https://x.com/ilyasut",
      favicon_url: favicon("x.com"),
      label: "@Twitter",
      twitter_handle: "ilyasut",
      tagline: "SSI + לשעבר OpenAI Chief Scientist",
    },
  },
  {
    id: "twitter-ethanmollick",
    name: "@emollick (Ethan Mollick)",
    url: "https://x.com/emollick",
    type: "twitter_account",
    tier: 1,
    lang: "en",
    topics: ["tools", "business", "education"],
    reliability: 5,
    credit: {
      display_name: "Ethan Mollick",
      profile_url: "https://x.com/emollick",
      favicon_url: favicon("x.com"),
      label: "@Twitter",
      twitter_handle: "emollick",
      tagline: "Wharton prof — שימושים מעשיים, מאוד נגיש",
    },
  },
  {
    id: "twitter-swyx",
    name: "@swyx (Shawn Wang)",
    url: "https://x.com/swyx",
    type: "twitter_account",
    tier: 1,
    lang: "en",
    topics: ["tools", "agents", "open_source"],
    reliability: 4,
    credit: {
      display_name: "swyx",
      profile_url: "https://x.com/swyx",
      favicon_url: favicon("x.com"),
      label: "@Twitter",
      twitter_handle: "swyx",
      tagline: "AI Engineer — Latent Space podcast creator",
    },
  },
  {
    id: "twitter-andrewng",
    name: "@AndrewYNg (Andrew Ng)",
    url: "https://x.com/AndrewYNg",
    type: "twitter_account",
    tier: 1,
    lang: "en",
    topics: ["education", "LLMs", "research"],
    reliability: 5,
    credit: {
      display_name: "Andrew Ng",
      profile_url: "https://x.com/AndrewYNg",
      favicon_url: favicon("x.com"),
      label: "@Twitter",
      twitter_handle: "AndrewYNg",
      tagline: "DeepLearning.AI founder — AI education leader",
    },
  },
  {
    id: "twitter-fchollet",
    name: "@fchollet (François Chollet)",
    url: "https://x.com/fchollet",
    type: "twitter_account",
    tier: 2,
    lang: "en",
    topics: ["research", "LLMs", "safety"],
    reliability: 4,
    credit: {
      display_name: "François Chollet",
      profile_url: "https://x.com/fchollet",
      favicon_url: favicon("x.com"),
      label: "@Twitter",
      twitter_handle: "fchollet",
      tagline: "יוצר Keras — ARC-AGI benchmark",
    },
  },
  {
    id: "twitter-garymarcus",
    name: "@GaryMarcus",
    url: "https://x.com/GaryMarcus",
    type: "twitter_account",
    tier: 2,
    lang: "en",
    topics: ["LLMs", "policy", "safety"],
    reliability: 3,
    credit: {
      display_name: "Gary Marcus",
      profile_url: "https://x.com/GaryMarcus",
      favicon_url: favicon("x.com"),
      label: "@Twitter",
      twitter_handle: "GaryMarcus",
      tagline: "מבקר AI — counterbalance חשוב להייפ",
    },
  },
  {
    id: "twitter-jeremyhoward",
    name: "@jeremyphoward (Jeremy Howard)",
    url: "https://x.com/jeremyphoward",
    type: "twitter_account",
    tier: 2,
    lang: "en",
    topics: ["education", "open_source", "LLMs"],
    reliability: 4,
    credit: {
      display_name: "Jeremy Howard",
      profile_url: "https://x.com/jeremyphoward",
      favicon_url: favicon("x.com"),
      label: "@Twitter",
      twitter_handle: "jeremyphoward",
      tagline: "fast.ai founder — AI education advocate",
    },
  },
  {
    id: "twitter-drfeifei",
    name: "@drfeifei (Fei-Fei Li)",
    url: "https://x.com/drfeifei",
    type: "twitter_account",
    tier: 2,
    lang: "en",
    topics: ["research", "vision", "policy"],
    reliability: 4,
    credit: {
      display_name: "Fei-Fei Li",
      profile_url: "https://x.com/drfeifei",
      favicon_url: favicon("x.com"),
      label: "@Twitter",
      twitter_handle: "drfeifei",
      tagline: "Stanford — \"godmother of AI\", computer vision",
    },
  },
  {
    id: "twitter-kaifulee",
    name: "@kaifulee (Kai-Fu Lee)",
    url: "https://x.com/kaifulee",
    type: "twitter_account",
    tier: 2,
    lang: "en",
    topics: ["business", "policy", "LLMs"],
    reliability: 4,
    credit: {
      display_name: "Kai-Fu Lee",
      profile_url: "https://x.com/kaifulee",
      favicon_url: favicon("x.com"),
      label: "@Twitter",
      twitter_handle: "kaifulee",
      tagline: "01.AI CEO + AI Superpowers author",
    },
  },
  {
    id: "twitter-natolambert",
    name: "@natolambert (Nathan Lambert)",
    url: "https://x.com/natolambert",
    type: "twitter_account",
    tier: 1,
    lang: "en",
    topics: ["research", "LLMs", "safety"],
    reliability: 5,
    credit: {
      display_name: "Nathan Lambert",
      profile_url: "https://x.com/natolambert",
      favicon_url: favicon("x.com"),
      label: "@Twitter",
      twitter_handle: "natolambert",
      tagline: "RLHF researcher — Interconnects newsletter",
    },
  },
  {
    id: "twitter-simonw",
    name: "@simonw (Simon Willison)",
    url: "https://x.com/simonw",
    type: "twitter_account",
    tier: 2,
    lang: "en",
    topics: ["tools", "open_source"],
    reliability: 5,
    credit: {
      display_name: "Simon Willison",
      profile_url: "https://x.com/simonw",
      favicon_url: favicon("x.com"),
      label: "@Twitter",
      twitter_handle: "simonw",
      tagline: "Django creator — LLM tools deep dives",
    },
  },
  {
    id: "twitter-rasbt",
    name: "@rasbt (Sebastian Raschka)",
    url: "https://x.com/rasbt",
    type: "twitter_account",
    tier: 2,
    lang: "en",
    topics: ["research", "LLMs", "education"],
    reliability: 5,
    credit: {
      display_name: "Sebastian Raschka",
      profile_url: "https://x.com/rasbt",
      favicon_url: favicon("x.com"),
      label: "@Twitter",
      twitter_handle: "rasbt",
      tagline: "ML researcher — Ahead of AI newsletter",
    },
  },
  {
    id: "twitter-mattxwolfe",
    name: "@mattxwolfe (Matt Wolfe)",
    url: "https://x.com/mattxwolfe",
    type: "twitter_account",
    tier: 2,
    lang: "en",
    topics: ["tools", "LLMs"],
    reliability: 3,
    credit: {
      display_name: "Matt Wolfe",
      profile_url: "https://x.com/mattxwolfe",
      favicon_url: favicon("x.com"),
      label: "@Twitter",
      twitter_handle: "mattxwolfe",
      tagline: "AI tools & news — YouTube + Twitter",
    },
  },
  // חשבונות חברות רשמיים
  {
    id: "twitter-anthropic",
    name: "@AnthropicAI",
    url: "https://x.com/AnthropicAI",
    type: "twitter_account",
    tier: 1,
    lang: "en",
    topics: ["LLMs", "safety"],
    reliability: 5,
    credit: {
      display_name: "@AnthropicAI",
      profile_url: "https://x.com/AnthropicAI",
      favicon_url: favicon("x.com"),
      label: "@Twitter",
      twitter_handle: "AnthropicAI",
      tagline: "הכרזות רשמיות Claude",
    },
  },
  {
    id: "twitter-openai",
    name: "@OpenAI",
    url: "https://x.com/OpenAI",
    type: "twitter_account",
    tier: 1,
    lang: "en",
    topics: ["LLMs", "tools"],
    reliability: 5,
    credit: {
      display_name: "@OpenAI",
      profile_url: "https://x.com/OpenAI",
      favicon_url: favicon("x.com"),
      label: "@Twitter",
      twitter_handle: "OpenAI",
      tagline: "הכרזות רשמיות GPT, Sora",
    },
  },
  {
    id: "twitter-googledeepmi",
    name: "@GoogleDeepMind",
    url: "https://x.com/GoogleDeepMind",
    type: "twitter_account",
    tier: 1,
    lang: "en",
    topics: ["research", "LLMs"],
    reliability: 5,
    credit: {
      display_name: "@GoogleDeepMind",
      profile_url: "https://x.com/GoogleDeepMind",
      favicon_url: favicon("x.com"),
      label: "@Twitter",
      twitter_handle: "GoogleDeepMind",
      tagline: "הכרזות רשמיות DeepMind",
    },
  },
  {
    id: "twitter-metaai",
    name: "@MetaAI",
    url: "https://x.com/MetaAI",
    type: "twitter_account",
    tier: 1,
    lang: "en",
    topics: ["LLMs", "open_source"],
    reliability: 5,
    credit: {
      display_name: "@MetaAI",
      profile_url: "https://x.com/MetaAI",
      favicon_url: favicon("x.com"),
      label: "@Twitter",
      twitter_handle: "MetaAI",
      tagline: "הכרזות רשמיות Meta AI ו-Llama",
    },
  },
  {
    id: "twitter-huggingface",
    name: "@huggingface",
    url: "https://x.com/huggingface",
    type: "twitter_account",
    tier: 1,
    lang: "en",
    topics: ["open_source", "tools"],
    reliability: 5,
    credit: {
      display_name: "@huggingface",
      profile_url: "https://x.com/huggingface",
      favicon_url: favicon("x.com"),
      label: "@Twitter",
      twitter_handle: "huggingface",
      tagline: "הכרזות רשמיות Hugging Face",
    },
  },
  {
    id: "twitter-mistralai",
    name: "@MistralAI",
    url: "https://x.com/MistralAI",
    type: "twitter_account",
    tier: 1,
    lang: "en",
    topics: ["LLMs", "open_source"],
    reliability: 5,
    credit: {
      display_name: "@MistralAI",
      profile_url: "https://x.com/MistralAI",
      favicon_url: favicon("x.com"),
      label: "@Twitter",
      twitter_handle: "MistralAI",
      tagline: "הכרזות רשמיות Mistral",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // TIER 2 — פורומים וקהילות
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: "reddit-machinelearning",
    name: "r/MachineLearning",
    url: "https://www.reddit.com/r/MachineLearning",
    rss: "https://www.reddit.com/r/MachineLearning/top/.rss?t=week",
    type: "forum",
    tier: 1,
    lang: "en",
    topics: ["research", "LLMs"],
    reliability: 3,
    notes: "1.8M+ members — דיון אקדמי-טכני גבוה",
    credit: {
      display_name: "r/MachineLearning",
      profile_url: "https://www.reddit.com/r/MachineLearning",
      favicon_url: favicon("reddit.com"),
      label: "Reddit",
      tagline: "קהילת ML — דיון אקדמי-טכני גבוה",
    },
  },
  {
    id: "reddit-localllama",
    name: "r/LocalLLaMA",
    url: "https://www.reddit.com/r/LocalLLaMA",
    rss: "https://www.reddit.com/r/LocalLLaMA/top/.rss?t=week",
    type: "forum",
    tier: 1,
    lang: "en",
    topics: ["open_source", "LLMs", "tools"],
    reliability: 3,
    notes: "קהילת open source LLMs — ידיעות ראשונות על מודלים",
    credit: {
      display_name: "r/LocalLLaMA",
      profile_url: "https://www.reddit.com/r/LocalLLaMA",
      favicon_url: favicon("reddit.com"),
      label: "Reddit",
      tagline: "קהילת open source LLMs",
    },
  },
  {
    id: "reddit-artificial",
    name: "r/artificial",
    url: "https://www.reddit.com/r/artificial",
    rss: "https://www.reddit.com/r/artificial/top/.rss?t=week",
    type: "forum",
    tier: 2,
    lang: "en",
    topics: ["LLMs", "tools", "policy"],
    reliability: 3,
    credit: {
      display_name: "r/artificial",
      profile_url: "https://www.reddit.com/r/artificial",
      favicon_url: favicon("reddit.com"),
      label: "Reddit",
      tagline: "קהילת AI כללית — 800K+ members",
    },
  },
  {
    id: "reddit-singularity",
    name: "r/singularity",
    url: "https://www.reddit.com/r/singularity",
    rss: "https://www.reddit.com/r/singularity/top/.rss?t=week",
    type: "forum",
    tier: 2,
    lang: "en",
    topics: ["LLMs", "safety", "research"],
    reliability: 3,
    notes: "מוטה להייפ — אבל מוצא ידיעות מהר",
    credit: {
      display_name: "r/singularity",
      profile_url: "https://www.reddit.com/r/singularity",
      favicon_url: favicon("reddit.com"),
      label: "Reddit",
      tagline: "מוטה להייפ — אבל ידיעות מהר",
    },
  },
  {
    id: "hacker-news-ai",
    name: "Hacker News (AI)",
    url: "https://news.ycombinator.com",
    rss: "https://hnrss.org/frontpage?points=50",
    type: "forum",
    tier: 1,
    lang: "en",
    topics: ["tools", "startups", "research", "open_source"],
    reliability: 4,
    notes: "HN עם סף 100+ נקודות",
    credit: {
      display_name: "Hacker News",
      profile_url: "https://news.ycombinator.com",
      favicon_url: favicon("ycombinator.com"),
      label: "Forum",
      tagline: "Hacker News — signal:noise גבוה",
    },
  },
  {
    id: "lesswrong-ai",
    name: "LessWrong AI",
    url: "https://www.lesswrong.com/tag/ai",
    rss: "https://www.lesswrong.com/feed.xml?view=curated",
    type: "forum",
    tier: 2,
    lang: "en",
    topics: ["safety", "research"],
    reliability: 4,
    credit: {
      display_name: "LessWrong",
      profile_url: "https://www.lesswrong.com/tag/ai",
      favicon_url: favicon("lesswrong.com"),
      label: "Forum",
      tagline: "AI safety + alignment — קהילה איכותית",
    },
  },
  {
    id: "alignment-forum",
    name: "Alignment Forum",
    url: "https://www.alignmentforum.org",
    rss: "https://www.alignmentforum.org/feed.xml",
    type: "forum",
    tier: 2,
    lang: "en",
    topics: ["safety", "research"],
    reliability: 5,
    credit: {
      display_name: "Alignment Forum",
      profile_url: "https://www.alignmentforum.org",
      favicon_url: favicon("alignmentforum.org"),
      label: "Forum",
      tagline: "AI alignment — הכי אמין בתחום safety",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // TIER 2 — YouTube
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: "youtube-two-minute-papers",
    name: "Two Minute Papers",
    url: "https://www.youtube.com/@TwoMinutePapers",
    rss: "https://www.youtube.com/feeds/videos.xml?channel_id=UCbfYPyITQ-7l4upoX8nvctg",
    type: "youtube",
    tier: 2,
    lang: "en",
    topics: ["research", "vision", "LLMs"],
    reliability: 4,
    credit: {
      display_name: "Two Minute Papers",
      profile_url: "https://www.youtube.com/@TwoMinutePapers",
      favicon_url: favicon("youtube.com"),
      label: "YouTube",
      tagline: "מחקרים אקדמיים בצורה נגישה ומהירה",
    },
  },
  {
    id: "youtube-yannic-kilcher",
    name: "Yannic Kilcher",
    url: "https://www.youtube.com/@YannicKilcher",
    rss: "https://www.youtube.com/feeds/videos.xml?channel_id=UCZHmQk67mSJgfCCTn7xBfew",
    type: "youtube",
    tier: 2,
    lang: "en",
    topics: ["research", "LLMs"],
    reliability: 4,
    credit: {
      display_name: "Yannic Kilcher",
      profile_url: "https://www.youtube.com/@YannicKilcher",
      favicon_url: favicon("youtube.com"),
      label: "YouTube",
      tagline: "הסבר עמוק של papers — טכני מאוד",
    },
  },
  {
    id: "youtube-ai-explained",
    name: "AI Explained",
    url: "https://www.youtube.com/@aiexplained-official",
    rss: "https://www.youtube.com/feeds/videos.xml?channel_id=UCNJ1Ymd5yFuUPtn21xtRbbw",
    type: "youtube",
    tier: 2,
    lang: "en",
    topics: ["LLMs", "research"],
    reliability: 4,
    credit: {
      display_name: "AI Explained",
      profile_url: "https://www.youtube.com/@aiexplained-official",
      favicon_url: favicon("youtube.com"),
      label: "YouTube",
      tagline: "ניתוח עדכוני AI — נגיש ומהיר",
    },
  },
  {
    id: "youtube-lex-fridman",
    name: "Lex Fridman Podcast",
    url: "https://www.youtube.com/@lexfridman",
    rss: "https://lexfridman.com/feed/podcast",
    type: "youtube",
    tier: 2,
    lang: "en",
    topics: ["LLMs", "research", "policy"],
    reliability: 4,
    credit: {
      display_name: "Lex Fridman",
      profile_url: "https://www.youtube.com/@lexfridman",
      favicon_url: favicon("youtube.com"),
      label: "YouTube",
      twitter_handle: "lexfridman",
      tagline: "ראיונות עומק עם מובילי AI",
    },
  },
  {
    id: "youtube-3blue1brown",
    name: "3Blue1Brown",
    url: "https://www.youtube.com/@3blue1brown",
    rss: "https://www.youtube.com/feeds/videos.xml?channel_id=UCYO_jab_esuFRV4b17AJtAg",
    type: "youtube",
    tier: 2,
    lang: "en",
    topics: ["education", "research"],
    reliability: 5,
    credit: {
      display_name: "3Blue1Brown",
      profile_url: "https://www.youtube.com/@3blue1brown",
      favicon_url: favicon("youtube.com"),
      label: "YouTube",
      tagline: "Grant Sanderson — מתמטיקה + neural networks visually",
    },
  },
  {
    id: "youtube-deeplearningai",
    name: "DeepLearning.AI",
    url: "https://www.youtube.com/@DeepLearningAI",
    rss: "https://www.youtube.com/feeds/videos.xml?channel_id=UCcIXc5mABovA9PFe3WdIPGg",
    type: "youtube",
    tier: 2,
    lang: "en",
    topics: ["education", "LLMs"],
    reliability: 5,
    credit: {
      display_name: "DeepLearning.AI",
      profile_url: "https://www.youtube.com/@DeepLearningAI",
      favicon_url: favicon("youtube.com"),
      label: "YouTube",
      tagline: "Andrew Ng's educational channel",
    },
  },
  {
    id: "youtube-matt-wolfe",
    name: "Matt Wolfe",
    url: "https://www.youtube.com/@MattWolfe",
    rss: "https://www.youtube.com/feeds/videos.xml?channel_id=UCPkI58RNpBFqFe25cP-u-7Q",
    type: "youtube",
    tier: 2,
    lang: "en",
    topics: ["tools", "LLMs"],
    reliability: 3,
    credit: {
      display_name: "Matt Wolfe",
      profile_url: "https://www.youtube.com/@MattWolfe",
      favicon_url: favicon("youtube.com"),
      label: "YouTube",
      tagline: "AI tools & news — popular creator",
    },
  },
  {
    id: "youtube-dwarkesh",
    name: "Dwarkesh Patel",
    url: "https://www.youtube.com/@Dwarkesh_Patel",
    rss: "https://www.youtube.com/feeds/videos.xml?channel_id=UCFgZz_h5DHgmqes5yI0Eqig",
    type: "youtube",
    tier: 2,
    lang: "en",
    topics: ["research", "LLMs", "policy"],
    reliability: 4,
    credit: {
      display_name: "Dwarkesh Patel",
      profile_url: "https://www.youtube.com/@Dwarkesh_Patel",
      favicon_url: favicon("youtube.com"),
      label: "YouTube",
      tagline: "ראיונות עומק עם AI researchers + founders",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // TIER 2 — פודקאסטים
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: "podcast-latent-space",
    name: "Latent Space Podcast",
    url: "https://www.latent.space/podcast",
    rss: "https://api.substack.com/feed/podcast/1084089.rss",
    type: "podcast",
    tier: 1,
    lang: "en",
    topics: ["agents", "tools", "LLMs"],
    reliability: 5,
    credit: {
      display_name: "Latent Space",
      profile_url: "https://www.latent.space/podcast",
      favicon_url: favicon("latent.space"),
      label: "Podcast",
      twitter_handle: "latentspacepod",
      tagline: "swyx & Alessio — for AI engineers",
    },
  },
  {
    id: "podcast-practical-ai",
    name: "Practical AI Podcast",
    url: "https://changelog.com/practicalai",
    rss: "https://changelog.com/practicalai/feed",
    type: "podcast",
    tier: 2,
    lang: "en",
    topics: ["LLMs", "tools", "education"],
    reliability: 4,
    credit: {
      display_name: "Practical AI",
      profile_url: "https://changelog.com/practicalai",
      favicon_url: favicon("changelog.com"),
      label: "Podcast",
      tagline: "ML, DL, MLOps, LLMs — practical focus",
    },
  },
  {
    id: "podcast-lex-fridman",
    name: "Lex Fridman Podcast",
    url: "https://lexfridman.com/podcast",
    rss: "https://lexfridman.com/feed/podcast",
    type: "podcast",
    tier: 2,
    lang: "en",
    topics: ["research", "LLMs", "policy"],
    reliability: 4,
    credit: {
      display_name: "Lex Fridman",
      profile_url: "https://lexfridman.com/podcast",
      favicon_url: favicon("lexfridman.com"),
      label: "Podcast",
      twitter_handle: "lexfridman",
      tagline: "ראיונות עומק — 4.2M subscribers",
    },
  },
  {
    id: "podcast-eye-on-ai",
    name: "Eye on AI",
    url: "https://www.eye-on.ai/podcast",
    rss: "https://feeds.simplecast.com/eyeonai",
    type: "podcast",
    tier: 2,
    lang: "en",
    topics: ["policy", "business", "LLMs"],
    reliability: 4,
    credit: {
      display_name: "Eye on AI",
      profile_url: "https://www.eye-on.ai/podcast",
      favicon_url: favicon("eye-on.ai"),
      label: "Podcast",
      tagline: "Craig S. Smith (ex-NYT) — ethics & policy",
    },
  },
  {
    id: "podcast-the-ai-daily-brief",
    name: "The AI Daily Brief",
    url: "https://www.nathanlabenz.com/podcast",
    type: "podcast",
    tier: 2,
    lang: "en",
    topics: ["LLMs", "business"],
    reliability: 3,
    credit: {
      display_name: "AI Daily Brief",
      profile_url: "https://www.nathanlabenz.com/podcast",
      favicon_url: favicon("nathanlabenz.com"),
      label: "Podcast",
      tagline: "daily digestible AI updates",
    },
  },
  {
    id: "podcast-no-priors",
    name: "No Priors (Sarah Guo & Elad Gil)",
    url: "https://www.no-priors.com",
    rss: "https://feeds.simplecast.com/4mhBMqQR",
    type: "podcast",
    tier: 2,
    lang: "en",
    topics: ["startups", "business", "LLMs"],
    reliability: 4,
    credit: {
      display_name: "No Priors",
      profile_url: "https://www.no-priors.com",
      favicon_url: favicon("no-priors.com"),
      label: "Podcast",
      tagline: "Sarah Guo & Elad Gil — AI startups & VC",
    },
  },
  {
    id: "podcast-dwarkesh",
    name: "Dwarkesh Podcast",
    url: "https://www.dwarkeshpatel.com/podcast",
    rss: "https://api.substack.com/feed/podcast/1054957.rss",
    type: "podcast",
    tier: 2,
    lang: "en",
    topics: ["research", "LLMs"],
    reliability: 4,
    credit: {
      display_name: "Dwarkesh Podcast",
      profile_url: "https://www.dwarkeshpatel.com/podcast",
      favicon_url: favicon("dwarkeshpatel.com"),
      label: "Podcast",
      tagline: "ראיונות עומק עם top AI researchers",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // TIER 2 — AI Safety & Policy
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: "cais-blog",
    name: "Center for AI Safety (CAIS)",
    url: "https://safe.ai/research",
    rss: "https://safe.ai/rss",
    type: "research_org",
    tier: 2,
    lang: "en",
    topics: ["safety", "research"],
    reliability: 5,
    credit: {
      display_name: "CAIS",
      profile_url: "https://safe.ai/research",
      favicon_url: favicon("safe.ai"),
      label: "Research",
      tagline: "Center for AI Safety — multi-disciplinary research",
    },
  },
  {
    id: "miri-blog",
    name: "MIRI (Machine Intelligence Research Institute)",
    url: "https://intelligence.org/research",
    type: "research_org",
    tier: 3,
    lang: "en",
    topics: ["safety", "research"],
    reliability: 4,
    credit: {
      display_name: "MIRI",
      profile_url: "https://intelligence.org/research",
      favicon_url: favicon("intelligence.org"),
      label: "Research",
      tagline: "AI alignment research — long-term safety",
    },
  },
  {
    id: "hai-stanford",
    name: "Stanford HAI",
    url: "https://hai.stanford.edu/news",
    rss: "https://hai.stanford.edu/rss.xml",
    type: "research_org",
    tier: 2,
    lang: "en",
    topics: ["policy", "safety", "research"],
    reliability: 5,
    credit: {
      display_name: "Stanford HAI",
      profile_url: "https://hai.stanford.edu/news",
      favicon_url: favicon("stanford.edu"),
      label: "Research",
      tagline: "Stanford Human-Centered AI Institute",
    },
  },
  {
    id: "eleutherai",
    name: "EleutherAI Blog",
    url: "https://blog.eleuther.ai",
    rss: "https://blog.eleuther.ai/rss.xml",
    type: "research_org",
    tier: 2,
    lang: "en",
    topics: ["open_source", "research", "safety"],
    reliability: 4,
    credit: {
      display_name: "EleutherAI",
      profile_url: "https://blog.eleuther.ai",
      favicon_url: favicon("eleuther.ai"),
      label: "Research",
      tagline: "open source AI research collective",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // TIER 2 — GitHub + כלים
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: "github-trending-ai",
    name: "GitHub Trending (Python/AI)",
    url: "https://github.com/trending/python?since=weekly",
    type: "github",
    tier: 2,
    lang: "en",
    topics: ["open_source", "tools"],
    reliability: 4,
    credit: {
      display_name: "GitHub Trending",
      profile_url: "https://github.com/trending/python?since=weekly",
      favicon_url: favicon("github.com"),
      label: "GitHub",
      tagline: "repos Python trending שבועי",
    },
  },
  {
    id: "product-hunt-ai",
    name: "Product Hunt AI",
    url: "https://www.producthunt.com/topics/artificial-intelligence",
    rss: "https://www.producthunt.com/topics/artificial-intelligence/posts/feed",
    type: "aggregator",
    tier: 3,
    lang: "en",
    topics: ["tools", "startups"],
    reliability: 3,
    credit: {
      display_name: "Product Hunt AI",
      profile_url: "https://www.producthunt.com/topics/artificial-intelligence",
      favicon_url: favicon("producthunt.com"),
      label: "Tools",
      tagline: "כלי AI חדשים — הרבה רעש אבל מוצא gems",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // TIER 2 — Discord Communities
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: "discord-openai",
    name: "OpenAI Discord",
    url: "https://discord.gg/openai",
    type: "discord",
    tier: 2,
    lang: "en",
    topics: ["LLMs", "tools"],
    reliability: 4,
    credit: {
      display_name: "OpenAI Discord",
      profile_url: "https://discord.gg/openai",
      favicon_url: favicon("discord.com"),
      label: "Discord",
      tagline: "ChatGPT, Sora, GPT developers community",
    },
  },
  {
    id: "discord-huggingface",
    name: "Hugging Face Discord",
    url: "https://discord.gg/huggingface",
    type: "discord",
    tier: 2,
    lang: "en",
    topics: ["open_source", "tools"],
    reliability: 4,
    credit: {
      display_name: "HF Discord",
      profile_url: "https://discord.gg/huggingface",
      favicon_url: favicon("discord.com"),
      label: "Discord",
      tagline: "ML community — ethics, technical help",
    },
  },
  {
    id: "discord-midjourney",
    name: "Midjourney Discord",
    url: "https://discord.gg/midjourney",
    type: "discord",
    tier: 2,
    lang: "en",
    topics: ["vision", "tools"],
    reliability: 3,
    credit: {
      display_name: "Midjourney Discord",
      profile_url: "https://discord.gg/midjourney",
      favicon_url: favicon("discord.com"),
      label: "Discord",
      tagline: "AI image generation community",
    },
  },
  {
    id: "discord-eleutherai",
    name: "EleutherAI Discord",
    url: "https://discord.gg/eleutherai",
    type: "discord",
    tier: 3,
    lang: "en",
    topics: ["open_source", "research"],
    reliability: 4,
    credit: {
      display_name: "EleutherAI Discord",
      profile_url: "https://discord.gg/eleutherai",
      favicon_url: favicon("discord.com"),
      label: "Discord",
      tagline: "open source AI research community",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // TIER 2 — מקורות ישראליים
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: "geektime-ai",
    name: "Geektime AI",
    url: "https://www.geektime.co.il/category/ai",
    rss: "https://www.geektime.co.il/feed",
    type: "israeli",
    tier: 2,
    lang: "he",
    topics: ["LLMs", "tools", "startups", "business"],
    reliability: 3,
    credit: {
      display_name: "Geektime",
      profile_url: "https://www.geektime.co.il/category/ai",
      favicon_url: favicon("geektime.co.il"),
      label: "מדיה ישראלית",
      tagline: "מדיה טכנולוגית ישראלית מובילה",
    },
  },
  {
    id: "ctech-ai",
    name: "CTech (Calcalist)",
    url: "https://www.calcalist.co.il/ctech",
    rss: "https://www.calcalist.co.il/rss.html",
    type: "israeli",
    tier: 2,
    lang: "he",
    topics: ["business", "startups", "LLMs"],
    reliability: 4,
    credit: {
      display_name: "CTech",
      profile_url: "https://www.calcalist.co.il/ctech",
      favicon_url: favicon("calcalist.co.il"),
      label: "מדיה ישראלית",
      tagline: "עסקי-טכנולוגי — חברות ישראליות",
    },
  },
  {
    id: "ivc-online",
    name: "IVC Online",
    url: "https://www.ivc-online.com",
    type: "israeli",
    tier: 3,
    lang: "en",
    topics: ["startups", "business"],
    reliability: 4,
    credit: {
      display_name: "IVC Online",
      profile_url: "https://www.ivc-online.com",
      favicon_url: favicon("ivc-online.com"),
      label: "ישראל",
      tagline: "VC ו-startups ישראלים",
    },
  },
  {
    id: "israel-innovation-authority",
    name: "רשות החדשנות הישראלית",
    url: "https://innovationisrael.org.il/news",
    type: "israeli",
    tier: 3,
    lang: "he",
    topics: ["policy", "business"],
    reliability: 4,
    credit: {
      display_name: "רשות החדשנות",
      profile_url: "https://innovationisrael.org.il/news",
      favicon_url: favicon("innovationisrael.org.il"),
      label: "ישראל",
      tagline: "מדיניות AI ממשלתית ישראלית",
    },
  },
  {
    id: "techtime-il",
    name: "Tech Time Israel",
    url: "https://www.techtime.co.il",
    type: "israeli",
    tier: 3,
    lang: "he",
    topics: ["startups", "tools", "LLMs"],
    reliability: 3,
    credit: {
      display_name: "Tech Time",
      profile_url: "https://www.techtime.co.il",
      favicon_url: favicon("techtime.co.il"),
      label: "מדיה ישראלית",
      tagline: "טכנולוגיה ישראלית — tech news",
    },
  },
]

// ─────────────────────────────────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────────────────────────────────

export const getByTier = (tier: 1 | 2 | 3) =>
  SOURCES.filter((s) => s.tier === tier)

export const getByType = (type: SourceType) =>
  SOURCES.filter((s) => s.type === type)

export const getByTopic = (topic: Topic) =>
  SOURCES.filter((s) => s.topics.includes(topic))

export const getRSSEnabled = () =>
  SOURCES.filter((s) => s.rss !== undefined)

export const getTier1WithRSS = () =>
  SOURCES.filter((s) => s.tier === 1 && s.rss !== undefined)

/**
 * מקורות לאיסוף יומי — מיקס מגוון:
 * - כל Tier 1 עם RSS
 * - Tier 2 מדיה וניוזלטרים עם RSS (מכסים הכרזות מכל החברות)
 * - לא כולל: Twitter, YouTube, Podcast, Discord (אין RSS מעשי)
 */
export const getIngestionSources = () =>
  SOURCES.filter((s) => {
    if (!s.rss) return false
    if (s.tier === 1) return true
    if (s.tier === 2 && (s.type === "media" || s.type === "newsletter")) return true
    return false
  })

export const getSourceById = (id: string) =>
  SOURCES.find((s) => s.id === id)

/** מקורות שמפרסמים preprints — טרם עברו peer review */
export const PREPRINT_SOURCE_IDS = new Set([
  "arxiv-cs-ai",
  "arxiv-cs-cl",
  "arxiv-cs-lg",
  "papers-with-code",
])

export const isPreprint = (sourceId: string) => PREPRINT_SOURCE_IDS.has(sourceId)

// ─────────────────────────────────────────────────────────────────────────────
// STATS
// ─────────────────────────────────────────────────────────────────────────────
export const STATS = {
  total: SOURCES.length,
  byTier: {
    tier1: getByTier(1).length,
    tier2: getByTier(2).length,
    tier3: getByTier(3).length,
  },
  withRSS: getRSSEnabled().length,
  tier1WithRSS: getTier1WithRSS().length,
  byType: {
    company_blog: getByType("company_blog").length,
    twitter_account: getByType("twitter_account").length,
    newsletter: getByType("newsletter").length,
    media: getByType("media").length,
    forum: getByType("forum").length,
    paper_tracker: getByType("paper_tracker").length,
    youtube: getByType("youtube").length,
    podcast: getByType("podcast").length,
    research_org: getByType("research_org").length,
    discord: getByType("discord").length,
    israeli: getByType("israeli").length,
    github: getByType("github").length,
    aggregator: getByType("aggregator").length,
  },
}
